//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyntaxticCode", Namespace="http://schemas.datacontract.org/2004/07/TCPSyntaxAnalyzerService")]
    [System.SerializableAttribute()]
    public partial class SyntaxticCode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((this.ScoreField.Equals(value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TCPSyntaxAnalyzer.ISyntaxAnalyzer")]
    public interface ISyntaxAnalyzer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyntaxAnalyzer/AnalyzeCode", ReplyAction="http://tempuri.org/ISyntaxAnalyzer/AnalyzeCodeResponse")]
        TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.SyntaxticCode AnalyzeCode(TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.SyntaxticCode code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISyntaxAnalyzer/AnalyzeCode", ReplyAction="http://tempuri.org/ISyntaxAnalyzer/AnalyzeCodeResponse")]
        System.Threading.Tasks.Task<TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.SyntaxticCode> AnalyzeCodeAsync(TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.SyntaxticCode code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISyntaxAnalyzerChannel : TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.ISyntaxAnalyzer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SyntaxAnalyzerClient : System.ServiceModel.ClientBase<TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.ISyntaxAnalyzer>, TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.ISyntaxAnalyzer {
        
        public SyntaxAnalyzerClient() {
        }
        
        public SyntaxAnalyzerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SyntaxAnalyzerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyntaxAnalyzerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SyntaxAnalyzerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.SyntaxticCode AnalyzeCode(TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.SyntaxticCode code) {
            return base.Channel.AnalyzeCode(code);
        }
        
        public System.Threading.Tasks.Task<TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.SyntaxticCode> AnalyzeCodeAsync(TCPSyntaxAnalyzerTest.TCPSyntaxAnalyzer.SyntaxticCode code) {
            return base.Channel.AnalyzeCodeAsync(code);
        }
    }
}
